In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('train.csv')

In [6]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [8]:
#filter row where age is greater than 25

In [14]:
filtered_df=df[df['Age']>25]
print(filtered_df)

     PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
6              7         0       1
..           ...       ...     ...
883          884         0       2
885          886         0       3
886          887         0       2
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
6                              McCarthy, Mr. Timothy J    male  54.0      0
..                                                 ...     ...   ...    ...
883                      Banfield, Mr. Frederick James    male  28.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
886                              Montvila, Rev. Juozas    male  27.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
6        0             17463  51.8625   E46        S
..     ...               ...      ...   ...      ...
883      0  C.A./SOTON 34068  10.5000   NaN        S
885      5            382652  29.1250   NaN        Q
886      0            211536  13.0000   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[413 rows x 12 columns]

In [16]:
print(filtered_df['Age'])

1      38.0
2      26.0
3      35.0
4      35.0
6      54.0
       ...
883    28.0
885    39.0
886    27.0
889    26.0
890    32.0
Name: Age, Length: 413, dtype: float64

In [18]:
#filter row where age is greater than 33 and sex is female

In [20]:
f_d=df[(df['Age']>33) & (df['Sex']=='female')]

In [44]:
print(f_d['Age'])

1      38.0
3      35.0
11     58.0
15     55.0
25     38.0
       ...
862    48.0
865    42.0
871    47.0
879    56.0
885    39.0
Name: Age, Length: 85, dtype: float64

In [46]:
#using isin()

In [48]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [50]:
filter_d=df[df['Embarked'].isin(['Q','C'])]
print(filter_d)

     PassengerId  Survived  Pclass  \
1              2         1       1
5              6         0       3
9             10         1       2
16            17         0       3
19            20         1       3
..           ...       ...     ...
875          876         1       3
879          880         1       1
885          886         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
5                                     Moran, Mr. James    male   NaN      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
16                                Rice, Master. Eugene    male   2.0      4
19                             Masselmani, Mrs. Fatima  female   NaN      0
..                                                 ...     ...   ...    ...
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch    Ticket     Fare Cabin Embarked
1        0  PC 17599  71.2833   C85        C
5        0    330877   8.4583   NaN        Q
9        0    237736  30.0708   NaN        C
16       1    382652  29.1250   NaN        Q
19       0      2649   7.2250   NaN        C
..     ...       ...      ...   ...      ...
875      0      2667   7.2250   NaN        C
879      1     11767  83.1583   C50        C
885      5    382652  29.1250   NaN        Q
889      0    111369  30.0000  C148        C
890      0    370376   7.7500   NaN        Q

[245 rows x 12 columns]

In [58]:
print(filter_d['Embarked'])

1      C
5      Q
9      C
16     Q
19     C
      ..
875    C
879    C
885    Q
889    C
890    Q
Name: Embarked, Length: 245, dtype: object

In [60]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [62]:
filter_dd=df[df['Age'].notnull()]
print(filter_dd)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
885          886         0       3
886          887         0       2
887          888         1       1
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
885      5            382652  29.1250   NaN        Q
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[714 rows x 12 columns]

In [64]:
#drop duplicate

In [66]:
df.shape

(891, 12)

In [68]:
df_no_duplicates=df.drop_duplicates()
print(df_no_duplicates)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [72]:
df_no_duplicates=df.drop_duplicates(subset=['Age'])
print(df_no_duplicates)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
5              6         0       3
..           ...       ...     ...
755          756         1       2
767          768         0       3
803          804         1       3
843          844         0       3
851          852         0       3

                                                  Name     Sex    Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.00      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.00      1
2                               Heikkinen, Miss. Laina  female  26.00      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.00      1
5                                     Moran, Mr. James    male    NaN      0
..                                                 ...     ...    ...    ...
755                          Hamalainen, Master. Viljo    male   0.67      1
767                                 Mangan, Miss. Mary  female  30.50      0
803                    Thomas, Master. Assad Alexander    male   0.42      0
843                         Lemberopolous, Mr. Peter L    male  34.50      0
851                                Svensson, Mr. Johan    male  74.00      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
5        0            330877   8.4583   NaN        Q
..     ...               ...      ...   ...      ...
755      1            250649  14.5000   NaN        S
767      0            364850   7.7500   NaN        Q
803      1              2625   8.5167   NaN        C
843      0              2683   6.4375   NaN        C
851      0            347060   7.7750   NaN        S

[89 rows x 12 columns]

In [82]:
df_no=df.drop_duplicates(subset='Age',keep='last')
print(df_no)

     PassengerId  Survived  Pclass                                      Name  \
33            34         0       2                     Wheadon, Mr. Edward H
111          112         0       3                      Zabour, Miss. Hileni
116          117         0       3                      Connors, Mr. Patrick
123          124         1       2                       Webber, Miss. Susan
125          126         1       3              Nicola-Yarred, Master. Elias
..           ...       ...     ...                                       ...
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked
33     male  66.0      0      0  C.A. 24579  10.5000   NaN        S
111  female  14.5      1      0        2665  14.4542   NaN        C
116    male  70.5      0      0      370369   7.7500   NaN        Q
123  female  32.5      0      0       27267  13.0000  E101        S
125    male  12.0      1      0        2651  11.2417   NaN        C
..      ...   ...    ...    ...         ...      ...   ...      ...
886    male  27.0      0      0      211536  13.0000   NaN        S
887  female  19.0      0      0      112053  30.0000   B42        S
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S
889    male  26.0      0      0      111369  30.0000  C148        C
890    male  32.0      0      0      370376   7.7500   NaN        Q

[89 rows x 12 columns]

In [86]:
df_no=df.drop_duplicates(keep=False)
print(df_no)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [88]:
#sort values

In [92]:
df_sorted=df.sort_values(by='Age')
print(df_sorted)

     PassengerId  Survived  Pclass                                      Name  \
803          804         1       3           Thomas, Master. Assad Alexander
755          756         1       2                 Hamalainen, Master. Viljo
644          645         1       3                    Baclini, Miss. Eugenie
469          470         1       3             Baclini, Miss. Helene Barbara
78            79         1       2             Caldwell, Master. Alden Gates
..           ...       ...     ...                                       ...
859          860         0       3                          Razi, Mr. Raihed
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"
868          869         0       3               van Melkebeke, Mr. Philemon
878          879         0       3                        Laleff, Mr. Kristo
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked
803    male  0.42      0      1        2625   8.5167   NaN        C
755    male  0.67      1      1      250649  14.5000   NaN        S
644  female  0.75      2      1        2666  19.2583   NaN        C
469  female  0.75      2      1        2666  19.2583   NaN        C
78     male  0.83      0      2      248738  29.0000   NaN        S
..      ...   ...    ...    ...         ...      ...   ...      ...
859    male   NaN      0      0        2629   7.2292   NaN        C
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S
868    male   NaN      0      0      345777   9.5000   NaN        S
878    male   NaN      0      0      349217   7.8958   NaN        S
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S

[891 rows x 12 columns]
803    0.42
755    0.67
644    0.75
469    0.75
78     0.83
       ...
859     NaN
863     NaN
868     NaN
878     NaN
888     NaN
Name: Age, Length: 891, dtype: float64

In [98]:
print(df_sorted.head(5))

     PassengerId  Survived  Pclass                             Name     Sex  \
803          804         1       3  Thomas, Master. Assad Alexander    male
755          756         1       2        Hamalainen, Master. Viljo    male
644          645         1       3           Baclini, Miss. Eugenie  female
469          470         1       3    Baclini, Miss. Helene Barbara  female
78            79         1       2    Caldwell, Master. Alden Gates    male

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked
803  0.42      0      1    2625   8.5167   NaN        C
755  0.67      1      1  250649  14.5000   NaN        S
644  0.75      2      1    2666  19.2583   NaN        C
469  0.75      2      1    2666  19.2583   NaN        C
78   0.83      0      2  248738  29.0000   NaN        S

In [100]:
df_sorted_desc=df.sort_values(by='Age',ascending=False)

In [104]:
print(df_sorted_desc.head(5))

     PassengerId  Survived  Pclass                                  Name  \
630          631         1       1  Barkworth, Mr. Algernon Henry Wilson
851          852         0       3                   Svensson, Mr. Johan
493          494         0       1               Artagaveytia, Mr. Ramon
96            97         0       1             Goldschmidt, Mr. George B
116          117         0       3                  Connors, Mr. Patrick

      Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked
630  male  80.0      0      0     27042  30.0000   A23        S
851  male  74.0      0      0    347060   7.7750   NaN        S
493  male  71.0      0      0  PC 17609  49.5042   NaN        C
96   male  71.0      0      0  PC 17754  34.6542    A5        C
116  male  70.5      0      0    370369   7.7500   NaN        Q

In [106]:
df_sorted_multi=df.sort_values(by=['Age','Pclass'],ascending=[False,True])

In [110]:
print(df_sorted_multi)

     PassengerId  Survived  Pclass                                      Name  \
630          631         1       1      Barkworth, Mr. Algernon Henry Wilson
851          852         0       3                       Svensson, Mr. Johan
96            97         0       1                 Goldschmidt, Mr. George B
493          494         0       1                   Artagaveytia, Mr. Ramon
116          117         0       3                      Connors, Mr. Patrick
..           ...       ...     ...                                       ...
859          860         0       3                          Razi, Mr. Raihed
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"
868          869         0       3               van Melkebeke, Mr. Philemon
878          879         0       3                        Laleff, Mr. Kristo
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked
630    male  80.0      0      0       27042  30.0000   A23        S
851    male  74.0      0      0      347060   7.7750   NaN        S
96     male  71.0      0      0    PC 17754  34.6542    A5        C
493    male  71.0      0      0    PC 17609  49.5042   NaN        C
116    male  70.5      0      0      370369   7.7500   NaN        Q
..      ...   ...    ...    ...         ...      ...   ...      ...
859    male   NaN      0      0        2629   7.2292   NaN        C
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S
868    male   NaN      0      0      345777   9.5000   NaN        S
878    male   NaN      0      0      349217   7.8958   NaN        S
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S

[891 rows x 12 columns]

In [112]:
#Group by
d=pd.read_csv('cars.csv')

In [114]:
d.head(4)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000

In [122]:
grouped=d.groupby('fuel')
avg_price=grouped['selling_price'].mean()

print(avg_price)

In [124]:
print(avg_price)

fuel
CNG       301017.491228
Diesel    791452.921627
LPG       200421.052632
Petrol    462441.061691
Name: selling_price, dtype: float64

In [130]:
#Applying multiple agg function
aggregate=grouped.agg({ 'selling_price':['mean','sum','max'] } )
print(aggregate)

        selling_price
                 mean         sum       max
fuel
CNG     301017.491228    17157997    545000
Diesel  791452.921627  3483975761   7200000
LPG     200421.052632     7616000    375000
Petrol  462441.061691  1679123495  10000000

In [132]:
#Grouping multiple columns

In [140]:
grouped_multi=d.groupby(['brand','fuel'])

In [144]:
avg_salary=grouped_multi['selling_price'].mean()

In [146]:
print(avg_salary)

brand          fuel
Ambassador     Diesel    1.240000e+05
Ashok          Diesel    3.000000e+05
Audi           Diesel    2.382829e+06
               Petrol    4.217800e+06
BMW            Diesel    4.164231e+06
               Petrol    1.991667e+06
Chevrolet      Diesel    3.493411e+05
               LPG       2.000000e+05
               Petrol    1.770154e+05
Daewoo         Petrol    7.700000e+04
Datsun         Petrol    3.146000e+05
Fiat           Diesel    3.406944e+05
               Petrol    1.500000e+05
Force          Diesel    8.875000e+05
Ford           Diesel    5.343071e+05
               Petrol    4.670288e+05
Honda          Diesel    6.733741e+05
               Petrol    5.634638e+05
Hyundai        CNG       1.608750e+05
               Diesel    5.814905e+05
               LPG       2.437857e+05
               Petrol    3.897427e+05
Isuzu          Diesel    1.942000e+06
Jaguar         Diesel    2.915465e+06
Jeep           Diesel    1.670900e+06
               Petrol    3.020000e+06
Kia            Diesel    1.504500e+06
Land           Diesel    3.608333e+06
Lexus          Petrol    5.150000e+06
MG             Petrol    1.783333e+06
Mahindra       Diesel    6.283432e+05
               Petrol    5.048438e+05
Maruti         CNG       3.274166e+05
               Diesel    5.598520e+05
               LPG       1.728636e+05
               Petrol    3.148199e+05
Mercedes-Benz  Diesel    2.607850e+06
               Petrol    2.077857e+06
Mitsubishi     Diesel    8.175000e+05
Nissan         Diesel    5.067916e+05
               Petrol    4.052121e+05
Opel           Petrol    6.800000e+04
Peugeot        Diesel    5.700000e+04
Renault        Diesel    5.828440e+05
               Petrol    3.524958e+05
Skoda          Diesel    5.693276e+05
               Petrol    6.551063e+05
Tata           CNG       1.550000e+05
               Diesel    3.546402e+05
               Petrol    3.666063e+05
Toyota         Diesel    9.487603e+05
               Petrol    9.924320e+05
Volkswagen     Diesel    5.074242e+05
               Petrol    4.777778e+05
Volvo          Diesel    3.170076e+06
               Petrol    1.000000e+07
Name: selling_price, dtype: float64