In [9]:
import pandas as pd

In [11]:
df=pd.read_csv('matches.csv')

In [13]:
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [15]:
df.corr()

ValueError: could not convert string to float: '2007/08'

In [17]:
df.corr(numeric_only=True)

                     id  result_margin  target_runs  target_overs
id             1.000000      -0.006853     0.238859      0.046388
result_margin -0.006853       1.000000     0.395120      0.030970
target_runs    0.238859       0.395120     1.000000      0.352361
target_overs   0.046388       0.030970     0.352361      1.000000

In [19]:
df.select_dtypes(include='number').corr()

                     id  result_margin  target_runs  target_overs
id             1.000000      -0.006853     0.238859      0.046388
result_margin -0.006853       1.000000     0.395120      0.030970
target_runs    0.238859       0.395120     1.000000      0.352361
target_overs   0.046388       0.030970     0.352361      1.000000