In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("titanic.csv")
df.head(5)

  Cabin            Ticket number  Survived
0   NaN         A/5 21171      5         0
1   C85          PC 17599      3         1
2   NaN  STON/O2. 3101282      6         1
3  C123            113803      3         1
4   NaN            373450      A         0

In [6]:
df.shape

(891, 4)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Cabin     204 non-null    object
 1   Ticket    891 non-null    object
 2   number    891 non-null    object
 3   Survived  891 non-null    int64
dtypes: int64(1), object(3)
memory usage: 28.0+ KB

In [10]:
df.describe()

         Survived
count  891.000000
mean     0.383838
std      0.486592
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      1.000000

In [12]:
df.isnull().sum()

Cabin       687
Ticket        0
number        0
Survived      0
dtype: int64

In [14]:
#dropna lost many data so fillna()

In [22]:
df.dropna()

           Cabin    Ticket number  Survived
1            C85  PC 17599      3         1
3           C123    113803      3         1
6            E46     17463      2         0
10            G6   PP 9549      1         1
11          C103    113783      1         1
..           ...       ...    ...       ...
871          D35     11751      1         1
872  B51 B53 B55       695      6         0
879          C50     11767      A         1
887          B42    112053      3         1
889         C148    111369      2         1

[204 rows x 4 columns]

In [18]:
df.shape

(891, 4)

In [48]:
df["Cabin"]=df["Cabin"].fillna("ccc")

In [50]:
df['Cabin']

0      ccc
1      ccc
2      ccc
3      ccc
4      ccc
      ...
886    ccc
887    ccc
888    ccc
889    ccc
890    ccc
Name: Cabin, Length: 891, dtype: object

In [52]:
#method='ffill'
#df["Cabin"]=df["Cabin"].fillna(method='ffill') #old
#df["Cabin"]=df["Cabin"].bfill()

In [54]:
df['Cabin']

0      ccc
1      ccc
2      ccc
3      ccc
4      ccc
      ...
886    ccc
887    ccc
888    ccc
889    ccc
890    ccc
Name: Cabin, Length: 891, dtype: object

In [56]:
df.isnull().sum()

Cabin       0
Ticket      0
number      0
Survived    0
dtype: int64

In [66]:
df['Cabin'].isnull().sum()

0