In [2]:
import pandas as pd

In [28]:
d=pd.read_csv('deliveries.csv')

In [68]:
df.head(3)
df.info()
df.shape
df['match_id'].head(600)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150460 entries, 0 to 150459
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          150460 non-null  int64
 1   inning            150460 non-null  int64
 2   batting_team      150460 non-null  object
 3   bowling_team      150460 non-null  object
 4   over              150460 non-null  int64
 5   ball              150460 non-null  int64
 6   batsman           150460 non-null  object
 7   non_striker       150460 non-null  object
 8   bowler            150460 non-null  object
 9   is_super_over     150460 non-null  int64
 10  wide_runs         150460 non-null  int64
 11  bye_runs          150460 non-null  int64
 12  legbye_runs       150460 non-null  int64
 13  noball_runs       150460 non-null  int64
 14  penalty_runs      150460 non-null  int64
 15  batsman_runs      150460 non-null  int64
 16  extra_runs        150460 non-null  int64
 17  total_runs        150460 non-null  int64
 18  player_dismissed  7438 non-null    object
 19  dismissal_kind    7438 non-null    object
 20  fielder           5369 non-null    object
dtypes: int64(13), object(8)
memory usage: 24.1+ MB

0      1
1      1
2      1
3      1
4      1
      ..
595    3
596    3
597    3
598    3
599    3
Name: match_id, Length: 600, dtype: int64

In [32]:
m=pd.read_csv('matches.csv')

In [70]:
df1.head(3)
df1.info()
df1.shape
df1['id'].head(40)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

0     335982
1     335983
2     335984
3     335985
4     335986
5     335987
6     335988
7     335989
8     335990
9     335991
10    335992
11    335993
12    335994
13    335995
14    335996
15    335997
16    335998
17    335999
18    336000
19    336001
20    336003
21    336034
22    336004
23    336005
24    336006
25    336007
26    336008
27    336009
28    336010
29    336011
30    336013
31    336014
32    336015
33    336016
34    336017
35    336018
36    336020
37    336021
38    336022
39    336023
Name: id, dtype: int64

In [50]:
merge_data=d.merge(m,left_on='match_id' ,right_on='id')

In [54]:
print(merge_data.shape)

(0, 41)

In [19]:
import pandas as pd
df1=pd.DataFrame({
    "id":[1,2,3,4,5,6,7,8,9,10],
    'names' : ["Alice","Bob","Charlie","David","Emma","Frank","Grace","Hannah","Ian","Julia"]
})
df1

   id    names
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David
4   5     Emma
5   6    Frank
6   7    Grace
7   8   Hannah
8   9      Ian
9  10    Julia

In [21]:

df2=pd.DataFrame({
     "id":[1,3,5,6,8,9],
    'Age':[23,53,32,42,63,28]
    
})
df2

   id  Age
0   1   23
1   3   53
2   5   32
3   6   42
4   8   63
5   9   28

In [23]:
#1. INNER JOIN (only matching rows)

In [25]:
pd.merge(df1,df2,on="id",how="inner")

   id    names  Age
0   1    Alice   23
1   3  Charlie   53
2   5     Emma   32
3   6    Frank   42
4   8   Hannah   63
5   9      Ian   28

In [27]:
pd.merge(df1,df2,on="id",how="left")

   id    names   Age
0   1    Alice  23.0
1   2      Bob   NaN
2   3  Charlie  53.0
3   4    David   NaN
4   5     Emma  32.0
5   6    Frank  42.0
6   7    Grace   NaN
7   8   Hannah  63.0
8   9      Ian  28.0
9  10    Julia   NaN

In [29]:
pd.merge(df1,df2,on="id",how="right")

   id    names  Age
0   1    Alice   23
1   3  Charlie   53
2   5     Emma   32
3   6    Frank   42
4   8   Hannah   63
5   9      Ian   28

In [31]:
pd.merge(df1,df2,on="id",how="outer")

   id    names   Age
0   1    Alice  23.0
1   2      Bob   NaN
2   3  Charlie  53.0
3   4    David   NaN
4   5     Emma  32.0
5   6    Frank  42.0
6   7    Grace   NaN
7   8   Hannah  63.0
8   9      Ian  28.0
9  10    Julia   NaN

In [33]:
df1=pd.read_csv("cars.csv")
df1

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [37]:
df2=pd.read_csv("Employee.csv")
df2

    ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

In [39]:
result=df1.join(df2)

In [41]:
result

,brand,km_driven,fuel,owner,selling_price,ID,Experience_Years,Age,Gender,Salary
0,Maruti,145500,Diesel,First Owner,450000,1.0,5.0,28.0,Female,250000.0
1,Skoda,120000,Diesel,Second Owner,370000,2.0,1.0,21.0,Male,50000.0
2,Honda,140000,Petrol,Third Owner,158000,3.0,3.0,23.0,Female,170000.0
3,Hyundai,127000,Diesel,First Owner,225000,4.0,2.0,22.0,Male,25000.0
4,Maruti,120000,Petrol,First Owner,130000,5.0,1.0,17.0,Male,10000.0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,Petrol,First Owner,320000,NaN,NaN,NaN,NaN,NaN
8124,Hyundai,119000,Diesel,Fourth & Above Owner,135000,NaN,NaN,NaN,NaN,NaN
8125,Maruti,120000,Diesel,First Owner,382000,NaN,NaN,NaN,NaN,NaN
8126,Tata,25000,Diesel,First Owner,290000,NaN,NaN,NaN,NaN,NaN
8127,Tata,25000,Diesel,First Owner,290000,NaN,NaN,NaN,NaN,NaN

In [43]:
pd.concat([df1,df2])

,brand,km_driven,fuel,owner,selling_price,ID,Experience_Years,Age,Gender,Salary
0,Maruti,145500.0,Diesel,First Owner,450000.0,NaN,NaN,NaN,NaN,NaN
1,Skoda,120000.0,Diesel,Second Owner,370000.0,NaN,NaN,NaN,NaN,NaN
2,Honda,140000.0,Petrol,Third Owner,158000.0,NaN,NaN,NaN,NaN,NaN
3,Hyundai,127000.0,Diesel,First Owner,225000.0,NaN,NaN,NaN,NaN,NaN
4,Maruti,120000.0,Petrol,First Owner,130000.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
30,NaN,NaN,NaN,NaN,NaN,31.0,10.0,34.0,Male,80000.0
31,NaN,NaN,NaN,NaN,NaN,32.0,15.0,54.0,Male,900000.0
32,NaN,NaN,NaN,NaN,NaN,33.0,20.0,55.0,Female,1540000.0
33,NaN,NaN,NaN,NaN,NaN,34.0,19.0,53.0,Female,9300000.0
34,NaN,NaN,NaN,NaN,NaN,35.0,16.0,49.0,Male,7600000.0

In [45]:
pd.concat([df1,df2],axis=1)

,brand,km_driven,fuel,owner,selling_price,ID,Experience_Years,Age,Gender,Salary
0,Maruti,145500,Diesel,First Owner,450000,1.0,5.0,28.0,Female,250000.0
1,Skoda,120000,Diesel,Second Owner,370000,2.0,1.0,21.0,Male,50000.0
2,Honda,140000,Petrol,Third Owner,158000,3.0,3.0,23.0,Female,170000.0
3,Hyundai,127000,Diesel,First Owner,225000,4.0,2.0,22.0,Male,25000.0
4,Maruti,120000,Petrol,First Owner,130000,5.0,1.0,17.0,Male,10000.0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,Petrol,First Owner,320000,NaN,NaN,NaN,NaN,NaN
8124,Hyundai,119000,Diesel,Fourth & Above Owner,135000,NaN,NaN,NaN,NaN,NaN
8125,Maruti,120000,Diesel,First Owner,382000,NaN,NaN,NaN,NaN,NaN
8126,Tata,25000,Diesel,First Owner,290000,NaN,NaN,NaN,NaN,NaN
8127,Tata,25000,Diesel,First Owner,290000,NaN,NaN,NaN,NaN,NaN

In [47]:
df1.append(df2)

AttributeError: 'DataFrame' object has no attribute 'append'

2059147.142857143