In [1]:
import pandas as pd

In [3]:
#read_csv

In [5]:
df=pd.read_csv("cars.csv")
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [7]:
#read_table

In [9]:
df=pd.read_table("data.txt")
df.head(10)

      name  age       city
0      Ivy   24     Mumbai
1   Hannah   40  Bangalore
2    Grace   34      Surat
3    Frank   24  Bangalore
4  Charlie   37  Hyderabad
5      Bob   23       Pune
6    Grace   23      Delhi
7    Grace   29      Delhi
8    Frank   37       Pune
9      Bob   32      Surat

In [11]:
#read txt file using csv()

In [13]:
df=pd.read_csv("data.txt")
df.head(3)

         name\tage\tcity
0        Ivy\t24\tMumbai
1  Hannah\t40\tBangalore
2       Grace\t34\tSurat

In [15]:
#read excel file

In [36]:
df=pd.read_excel("data.xlsx",sheet_name=[0,"Products",])
df

{0:        name  age       city
 0      Jack   28       Pune
 1       Ivy   23    Kolkata
 2     Grace   20     Jaipur
 3       Ivy   36  Bangalore
 4       Eve   35    Chennai
 5     Grace   24    Kolkata
 6      Jack   26      Delhi
 7      Jack   35    Chennai
 8       Bob   22  Bangalore
 9     Frank   37  Bangalore
 10    David   25      Surat
 11      Eve   32       Pune
 12    David   31      Surat
 13      Bob   23    Kolkata
 14  Charlie   25      Delhi
 15      Ivy   30      Surat
 16    Grace   26  Hyderabad
 17    Alice   39     Mumbai
 18    David   40     Jaipur
 19    Frank   38      Surat
 20   Hannah   24    Chennai
 21     Jack   23     Mumbai
 22     Jack   32    Kolkata
 23    Alice   33     Jaipur
 24      Ivy   27     Mumbai
 25   Hannah   18      Surat
 26    David   32      Delhi
 27    David   19     Jaipur
 28    Alice   39     Jaipur
 29     Jack   39     Mumbai
 30      Ivy   22    Kolkata
 31      Eve   23      Delhi
 32   Hannah   36     Jaipur
 33    David   40    Chennai
 34     Jack   34      Surat
 35      Bob   27    Chennai
 36      Bob   25  Bangalore
 37   Hannah   26  Hyderabad
 38    Grace   32      Surat
 39  Charlie   35     Nagpur
 40      Bob   30      Surat
 41    Frank   27     Nagpur
 42      Ivy   34    Kolkata
 43    Alice   26  Hyderabad
 44      Ivy   34       Pune
 45      Bob   19    Kolkata
 46      Bob   24       Pune
 47   Hannah   31     Mumbai
 48      Ivy   33  Hyderabad
 49  Charlie   23       Pune
 50     Jack   23  Hyderabad
 51      Bob   36     Jaipur
 52    David   37  Bangalore
 53    David   34      Surat
 54      Eve   21     Nagpur
 55    Alice   20     Nagpur
 56      Eve   36     Jaipur
 57    Grace   38    Kolkata
 58      Bob   22     Jaipur
 59     Jack   23      Surat,
 'Products':        product  price  quantity
 0    Product_1    319         3
 1    Product_2    674        16
 2    Product_3    482         1
 3    Product_4    854         3
 4    Product_5    674         7
 5    Product_6    947        16
 6    Product_7    780        15
 7    Product_8    969        12
 8    Product_9    838        18
 9   Product_10    438         6
 10  Product_11    132         8
 11  Product_12    158        18
 12  Product_13    725         9
 13  Product_14    210         9
 14  Product_15    496         1
 15  Product_16    477        19
 16  Product_17    191         1
 17  Product_18    297        20
 18  Product_19    178        11
 19  Product_20    317         6
 20  Product_21    774        12
 21  Product_22    598        18
 22  Product_23    924         4
 23  Product_24    338         2
 24  Product_25    212        12
 25  Product_26    790         2
 26  Product_27    533         2
 27  Product_28    347         6
 28  Product_29    526        14
 29  Product_30    130        10
 30  Product_31    803        17
 31  Product_32    742        12
 32  Product_33    101        20
 33  Product_34    274         6
 34  Product_35    456        10
 35  Product_36    795        16
 36  Product_37    990        11
 37  Product_38    110        11
 38  Product_39    732         1
 39  Product_40    603        12
 40  Product_41    396         9
 41  Product_42    286         2
 42  Product_43    707        11
 43  Product_44    940        15
 44  Product_45    820         9
 45  Product_46    802        17
 46  Product_47    561         2
 47  Product_48    146         9
 48  Product_49    627         9
 49  Product_50    113         3}

In [41]:
df.keys()

dict_keys([0, 'Products'])

In [ ]:
#pd.read_json(json_string)

In [43]:
df=pd.read_json("data.json")
df

    id     name  age       city
0    1      Eve   30    Chennai
1    2    David   20      Delhi
2    3    Grace   37  Bangalore
3    4      Ivy   21      Delhi
4    5  Charlie   33    Kolkata
5    6      Ivy   32  Bangalore
6    7     Jack   21  Hyderabad
7    8    Grace   18    Kolkata
8    9    Frank   40  Hyderabad
9   10    Grace   22      Surat
10  11     Jack   24       Pune
11  12      Bob   27      Delhi
12  13      Bob   22     Nagpur
13  14     Jack   37  Bangalore
14  15    Frank   18       Pune
15  16      Eve   32  Bangalore
16  17      Bob   29    Chennai
17  18      Eve   40     Nagpur
18  19    Alice   32    Chennai
19  20    Grace   19      Delhi
20  21    Grace   36     Jaipur
21  22    David   38       Pune
22  23  Charlie   31    Kolkata
23  24      Ivy   33     Nagpur
24  25      Ivy   33      Surat
25  26   Hannah   28    Chennai
26  27    David   24      Delhi
27  28      Ivy   28      Surat
28  29      Ivy   22  Hyderabad
29  30      Ivy   23      Delhi
30  31      Eve   35     Mumbai
31  32      Bob   22  Bangalore
32  33    Alice   36    Kolkata
33  34    David   24    Kolkata
34  35    Alice   31     Mumbai
35  36    Frank   30       Pune
36  37   Hannah   35     Jaipur
37  38    Alice   28      Delhi
38  39      Bob   27    Kolkata
39  40    David   30    Kolkata
40  41    David   22     Jaipur
41  42      Ivy   18     Mumbai
42  43     Jack   25    Chennai
43  44  Charlie   22  Hyderabad
44  45     Jack   40       Pune
45  46    David   38      Surat
46  47      Eve   38     Jaipur
47  48   Hannah   24       Pune
48  49  Charlie   29    Chennai
49  50      Ivy   19      Surat
50  51    Grace   39     Jaipur
51  52    Frank   22     Jaipur
52  53    Grace   36      Surat
53  54  Charlie   28    Kolkata
54  55      Ivy   23       Pune
55  56   Hannah   23     Nagpur
56  57    Grace   33  Bangalore
57  58      Ivy   19     Jaipur
58  59   Hannah   30  Hyderabad
59  60    David   33     Nagpur

In [45]:
#read_html

In [55]:
import requests
url = "https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)"
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
}
response = requests.get(url, headers=headers)

tables = pd.read_html(response.text)
print(len(tables))        # number of tables found on the page
print(tables[0].head())

2
  Country or territory  Population (1 July 2022)  Population (1 July 2023)  \
0                World                8021407192                8091734930
1                India                1425423212                1438069596
2             China[a]                1425179569                1422584933
3        United States                 341534046                 343477335
4            Indonesia                 278830529                 281190067

  Change (%) UN continental region[1] UN statistical subregion[1]
0     +0.88%                        –                           –
1     +0.89%                     Asia               Southern Asia
2     −0.18%                     Asia                Eastern Asia
3     +0.57%                 Americas            Northern America
4     +0.85%                     Asia          South-eastern Asia

/var/folders/zs/rgm7kj4s3bb8xy2q5rcm2pnh0000gn/T/ipykernel_1485/2654131035.py:9: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

In [57]:
#pd.Dataframe(dict)
#df.to_csv()
#df.to_excel()
#df.to_sql()
#df.to_json()

In [59]:
#pd.DataFrame(dict) is one of the easiest ways to make a DataFrame.
#Dictionary keys → columns, values → data.
#You can customize row index and column order.

In [63]:
data={
   "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 28],
    "City": ["Pune", "Mumbai", "Delhi"]
}
df=pd.DataFrame(data)
df

      Name  Age    City
0    Alice   25    Pune
1      Bob   30  Mumbai
2  Charlie   28   Delhi

In [65]:
#Custom row index

In [67]:
df=pd.DataFrame(data,index=['a','b','c'])
df

      Name  Age    City
a    Alice   25    Pune
b      Bob   30  Mumbai
c  Charlie   28   Delhi

In [69]:
#Selecting column order

In [91]:
df=pd.DataFrame(data,columns=['City','Name','Age'])
df

     City     Name  Age
0    Pune    Alice   25
1  Mumbai      Bob   30
2   Delhi  Charlie   28

In [73]:
#df.to_csv()

In [93]:
df.to_csv('people.csv',index=False)
df=pd.read_csv("people.csv")
df

     City     Name  Age
0    Pune    Alice   25
1  Mumbai      Bob   30
2   Delhi  Charlie   28

In [103]:
df.to_excel("people.xlsx")
df

     City     Name  Age
0    Pune    Alice   25
1  Mumbai      Bob   30
2   Delhi  Charlie   28

In [105]:
df.to_json("people.json")
df

     City     Name  Age
0    Pune    Alice   25
1  Mumbai      Bob   30
2   Delhi  Charlie   28