In [2]:
import pandas as pd

In [4]:
df=pd.read_csv("Employee.csv")

In [6]:
df.shape

(35, 5)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                35 non-null     int64
 1   Experience_Years  35 non-null     int64
 2   Age               35 non-null     int64
 3   Gender            35 non-null     object
 4   Salary            35 non-null     int64
dtypes: int64(4), object(1)
memory usage: 1.5+ KB

In [10]:
df.isnull().sum()

ID                  0
Experience_Years    0
Age                 0
Gender              0
Salary              0
dtype: int64

In [12]:
df.sample(5)

    ID  Experience_Years  Age  Gender    Salary
15  16                 4   27  Female     87000
12  13                14   39    Male   6000050
27  28                27   62  Female  10000000
21  22                 4   26    Male     25000
1    2                 1   21    Male     50000

In [14]:
#df.sort_values('col') sort by column in ascending order

In [16]:
df.sort_values('Age')

    ID  Experience_Years  Age  Gender    Salary
4    5                 1   17    Male     10000
26  27                 1   18    Male      3000
23  24                 1   21  Female      6000
1    2                 1   21    Male     50000
29  30                 2   21  Female      6100
7    8                 2   21  Female      9000
18  19                 2   21    Male     15000
3    4                 2   22    Male     25000
25  26                 3   22  Female     20000
2    3                 3   23  Female    170000
24  25                 4   23  Female      8900
14  15                 2   23    Male      7500
21  22                 4   26    Male     25000
10  11                 4   26  Female    250000
15  16                 4   27  Female     87000
0    1                 5   28  Female    250000
22  23                 5   29    Male   6845000
11  12                 6   29    Male   1400000
16  17                10   34  Female    930000
30  31                10   34    Male     80000
19  20                10   36    Male    330000
8    9                10   36  Female     61500
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
34  35                16   49    Male   7600000
33  34                19   53  Female   9300000
9   10                15   54  Female    650000
28  29                19   54  Female   5000000
6    7                19   54  Female    800000
31  32                15   54    Male    900000
20  21                15   54    Male   6570000
17  18                15   54  Female   7900000
32  33                20   55  Female   1540000
27  28                27   62  Female  10000000
5    6                25   62    Male   5001000

In [26]:
df.sort_values('Age',ascending=False).head(3)

    ID  Experience_Years  Age  Gender    Salary
5    6                25   62    Male   5001000
27  28                27   62  Female  10000000
32  33                20   55  Female   1540000

In [32]:
df.rename(columns={'Experience_Years':'experience'},inplace=True)

In [34]:
df.sort_values(['experience','Age'],ascending=[True,False])

    ID  experience  Age  Gender    Salary
1    2           1   21    Male     50000
23  24           1   21  Female      6000
26  27           1   18    Male      3000
4    5           1   17    Male     10000
14  15           2   23    Male      7500
3    4           2   22    Male     25000
7    8           2   21  Female      9000
18  19           2   21    Male     15000
29  30           2   21  Female      6100
2    3           3   23  Female    170000
25  26           3   22  Female     20000
15  16           4   27  Female     87000
10  11           4   26  Female    250000
21  22           4   26    Male     25000
24  25           4   23  Female      8900
22  23           5   29    Male   6845000
0    1           5   28  Female    250000
11  12           6   29    Male   1400000
8    9          10   36  Female     61500
19  20          10   36    Male    330000
16  17          10   34  Female    930000
30  31          10   34    Male     80000
13  14          11   40    Male    220100
12  13          14   39    Male   6000050
9   10          15   54  Female    650000
17  18          15   54  Female   7900000
20  21          15   54    Male   6570000
31  32          15   54    Male    900000
34  35          16   49    Male   7600000
6    7          19   54  Female    800000
28  29          19   54  Female   5000000
33  34          19   53  Female   9300000
32  33          20   55  Female   1540000
5    6          25   62    Male   5001000
27  28          27   62  Female  10000000

In [36]:
#df.nlargest(3,'col') get top 3 row by column

In [42]:
df.nlargest(3,'Salary')

    ID  experience  Age  Gender    Salary
27  28          27   62  Female  10000000
33  34          19   53  Female   9300000
17  18          15   54  Female   7900000

In [44]:
df.nsmallest(3,'Salary')

    ID  experience  Age  Gender  Salary
26  27           1   18    Male    3000
23  24           1   21  Female    6000
29  30           2   21  Female    6100

In [52]:
female_cols = df.filter(regex='Female$')
print(female_cols)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34]

In [54]:
df_filtered = df.filter(items=["Gender", "Salary"])
print(df_filtered)

    Gender    Salary
0   Female    250000
1     Male     50000
2   Female    170000
3     Male     25000
4     Male     10000
5     Male   5001000
6   Female    800000
7   Female      9000
8   Female     61500
9   Female    650000
10  Female    250000
11    Male   1400000
12    Male   6000050
13    Male    220100
14    Male      7500
15  Female     87000
16  Female    930000
17  Female   7900000
18    Male     15000
19    Male    330000
20    Male   6570000
21    Male     25000
22    Male   6845000
23  Female      6000
24  Female      8900
25  Female     20000
26    Male      3000
27  Female  10000000
28  Female   5000000
29  Female      6100
30    Male     80000
31    Male    900000
32  Female   1540000
33  Female   9300000
34    Male   7600000

In [56]:
df_gender = df.filter(like="Gender")
print(df_gender)

    Gender
0   Female
1     Male
2   Female
3     Male
4     Male
5     Male
6   Female
7   Female
8   Female
9   Female
10  Female
11    Male
12    Male
13    Male
14    Male
15  Female
16  Female
17  Female
18    Male
19    Male
20    Male
21    Male
22    Male
23  Female
24  Female
25  Female
26    Male
27  Female
28  Female
29  Female
30    Male
31    Male
32  Female
33  Female
34    Male

In [58]:
df[df['Salary']>50000]

    ID  experience  Age  Gender    Salary
0    1           5   28  Female    250000
2    3           3   23  Female    170000
5    6          25   62    Male   5001000
6    7          19   54  Female    800000
8    9          10   36  Female     61500
9   10          15   54  Female    650000
10  11           4   26  Female    250000
11  12           6   29    Male   1400000
12  13          14   39    Male   6000050
13  14          11   40    Male    220100
15  16           4   27  Female     87000
16  17          10   34  Female    930000
17  18          15   54  Female   7900000
19  20          10   36    Male    330000
20  21          15   54    Male   6570000
22  23           5   29    Male   6845000
27  28          27   62  Female  10000000
28  29          19   54  Female   5000000
30  31          10   34    Male     80000
31  32          15   54    Male    900000
32  33          20   55  Female   1540000
33  34          19   53  Female   9300000
34  35          16   49    Male   7600000

In [74]:
df.query("Gender == 'Male'")

    ID  experience  Age Gender   Salary
1    2           1   21   Male    50000
3    4           2   22   Male    25000
4    5           1   17   Male    10000
5    6          25   62   Male  5001000
11  12           6   29   Male  1400000
12  13          14   39   Male  6000050
13  14          11   40   Male   220100
14  15           2   23   Male     7500
18  19           2   21   Male    15000
19  20          10   36   Male   330000
20  21          15   54   Male  6570000
21  22           4   26   Male    25000
22  23           5   29   Male  6845000
26  27           1   18   Male     3000
30  31          10   34   Male    80000
31  32          15   54   Male   900000
34  35          16   49   Male  7600000

In [80]:
df.query("Age > 30 and Gender == 'Female'")

    ID  experience  Age  Gender    Salary
6    7          19   54  Female    800000
8    9          10   36  Female     61500
9   10          15   54  Female    650000
16  17          10   34  Female    930000
17  18          15   54  Female   7900000
27  28          27   62  Female  10000000
28  29          19   54  Female   5000000
32  33          20   55  Female   1540000
33  34          19   53  Female   9300000

In [84]:
df.loc[df["Gender"] == "Male", ["ID", "Age"]]

    ID  Age
1    2   21
3    4   22
4    5   17
5    6   62
11  12   29
12  13   39
13  14   40
14  15   23
18  19   21
19  20   36
20  21   54
21  22   26
22  23   29
26  27   18
30  31   34
31  32   54
34  35   49

In [88]:
df[df["Age"].isin([22, 21])]

    ID  experience  Age  Gender  Salary
1    2           1   21    Male   50000
3    4           2   22    Male   25000
7    8           2   21  Female    9000
18  19           2   21    Male   15000
23  24           1   21  Female    6000
25  26           3   22  Female   20000
29  30           2   21  Female    6100

In [90]:
df[df["Age"].between(28, 35)]

    ID  experience  Age  Gender   Salary
0    1           5   28  Female   250000
11  12           6   29    Male  1400000
16  17          10   34  Female   930000
22  23           5   29    Male  6845000
30  31          10   34    Male    80000

In [92]:
#df[df["Name"].str.startswith("A")]
#df[df["City"].str.contains("Pune")]